// save_plan: persist a Plan-mode plan to a markdown file under
// <workspace>/.deep-copilot/plans/ so the user can review, archive, or
// hand it to the Agent later. Designed to be allowed in Plan mode — it
// is the *deliverable* of a Plan-mode turn, not a code mutation.
//
// Returns a short text result for the model + a structured `path` line
// the webview card can pick up to render an "open file" affordance.
'use strict';

const fs   = require('fs');
const path = require('path');
const vscode = require('vscode');

const { wsRoot } = require('../utils/paths');
const { Logger } = require('../logger');

const PLANS_DIR_REL  = path.join('.deep-copilot', 'plans');
const MAX_BODY_BYTES = 256 * 1024; // 256 KB cap to avoid runaway writes.

function slugify(s) {
    return String(s || 'plan')
        .toLowerCase()
        .replace(/[^a-z0-9\u4e00-\u9fa5]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 48) || 'plan';
}

function ts() {
    const d = new Date();
    const pad = (n) => String(n).padStart(2, '0');
    return (
        d.getFullYear().toString() +
        pad(d.getMonth() + 1) +
        pad(d.getDate()) +
        'T' +
        pad(d.getHours()) +
        pad(d.getMinutes()) +
        pad(d.getSeconds())
    );
}

function asList(items) {
    if (!Array.isArray(items)) return [];
    return items.map(x => String(x ?? '').trim()).filter(Boolean);
}

function renderSteps(steps) {
    if (!Array.isArray(steps) || steps.length === 0) return '_(no steps provided)_';
    return steps.map((it, i) => {
        if (typeof it === 'string') return `${i + 1}. ${it}`;
        const title = String(it.title ?? it.text ?? it.step ?? '').trim() || `Step ${i + 1}`;
        const note  = String(it.note ?? it.detail ?? '').trim();
        return note ? `${i + 1}. **${title}** — ${note}` : `${i + 1}. ${title}`;
    }).join('\n');
}

function renderFiles(files) {
    if (!Array.isArray(files) || files.length === 0) return '_(none specified)_';
    return files.map(it => {
        if (typeof it === 'string') return `- \`${it}\``;
        const p = String(it.path ?? it.file ?? '').trim();
        const why = String(it.reason ?? it.why ?? it.note ?? '').trim();
        if (!p) return '';
        return why ? `- \`${p}\` — ${why}` : `- \`${p}\``;
    }).filter(Boolean).join('\n');
}

function renderBullets(items) {
    const list = asList(items);
    if (list.length === 0) return '_(none)_';
    return list.map(x => `- ${x}`).join('\n');
}

function buildMarkdown(args) {
    const title       = String(args.title || 'Untitled plan').trim();
    const goal        = String(args.goal || '').trim();
    const approach    = String(args.approach || args.summary || '').trim();
    const stepsMd     = renderSteps(args.steps);
    const filesMd     = renderFiles(args.files);
    const risksMd     = renderBullets(args.risks);
    const nextStepsMd = renderBullets(args.next_steps);
    const notes       = String(args.notes || '').trim();

    const meta = [
        `> Generated by Deep Copilot · Plan mode`,
        `> ${new Date().toISOString()}`,
    ].join('\n');

    return [
        `# ${title}`,
        '',
        meta,
        '',
        '## 目标 / Goal',
        goal || '_(not specified)_',
        '',
        '## 方案 / Approach',
        approach || '_(not specified)_',
        '',
        '## 步骤 / Steps',
        stepsMd,
        '',
        '## 涉及文件 / Affected files',
        filesMd,
        '',
        '## 风险与缓解 / Risks',
        risksMd,
        '',
        '## 下一步 / Next steps',
        nextStepsMd,
        notes ? '\n## 备注 / Notes\n' + notes : '',
        '',
    ].join('\n').replace(/\n{3,}/g, '\n\n');
}

async function toolSavePlan(args = {}) {
    const root = wsRoot();
    if (!root) return 'save_plan failed: no workspace folder is open.';

    const dirAbs = path.join(root, PLANS_DIR_REL);
    try { fs.mkdirSync(dirAbs, { recursive: true }); }
    catch (e) { return `save_plan failed to create directory: ${e.message}`; }

    const body = buildMarkdown(args);
    if (Buffer.byteLength(body, 'utf8') > MAX_BODY_BYTES) {
        return `save_plan failed: rendered markdown exceeds ${MAX_BODY_BYTES} bytes. Trim the input and retry.`;
    }

    const fileName = `plan-${ts()}-${slugify(args.title)}.md`;
    const fileAbs  = path.join(dirAbs, fileName);
    const fileRel  = path.posix.join('.deep-copilot', 'plans', fileName);

    try {
        fs.writeFileSync(fileAbs, body, 'utf8');
    } catch (e) {
        return `save_plan failed to write file: ${e.message}`;
    }

    try { Logger.info('SAVE_PLAN', { path: fileRel, bytes: Buffer.byteLength(body, 'utf8') }); } catch { /* ignore */ }

    // Best-effort: surface a clickable notification so the user can jump
    // to the saved plan immediately. Non-fatal if it fails (e.g. headless).
    try {
        const uri = vscode.Uri.file(fileAbs);
        vscode.window.showInformationMessage(
            `Deep Copilot · Plan saved to ${fileRel}`,
            'Open',
        ).then((sel) => {
            if (sel === 'Open') {
                vscode.window.showTextDocument(uri, { preview: false }).then(() => {}, () => {});
            }
        }, () => {});
    } catch { /* ignore */ }

    // Tool result for the model — concise, machine-parseable last line.
    return [
        `Plan saved to ${fileRel} (${Buffer.byteLength(body, 'utf8')} bytes).`,
        `The user can open it in the editor. In your final assistant message, reference this path so the user knows where the plan lives.`,
        `path: ${fileRel}`,
    ].join('\n');
}

module.exports = { toolSavePlan };
